-- Add new columns if they don't exist
ALTER TABLE users
ADD COLUMN IF NOT EXISTS full_name VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL UNIQUE,
ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS dob DATE,
ADD COLUMN IF NOT EXISTS blood_type ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'),
ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(255),
ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add indexes for commonly queried fields
CREATE INDEX IF NOT EXISTS idx_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_blood_type ON users(blood_type);
CREATE INDEX IF NOT EXISTS idx_is_available ON users(is_available); 